@startuml

skin rose

title Search Course Feature


start

:User enters command 'searchtutorial' command with a TUTORIAL;


if () then ([syntax valid])
    : Displays the number of persons in the filtered list in the response box;
    : Displays the profile of filtered persons;
else ([syntax invalid])
  endif

stop

@enduml
